### ISSUE TITLE
Appending existing file overwrites file & changes mtime

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#90]
Adding a file to archive with `createFileWriteStream` overwrites the existing file and changes the mtime, when using hyperdrive + random-access-file.

* This means we can't use mtime to check if files are updated because hyperdrive changes mtime (our own little observer effect). 
* Overwriting existing files seems like unwanted behavior. 

This may be a storage/raf issue.

*[Related issue](https://github.com/juliangruber/hyperdrive-import-files/issues/12) in hyperdrive-import-files*

**Comment by karissa** [comment]
This seems related to creating a 'clone' mode, rather than a 'latest' mode. Right now, hyperdrive operates in a 'latest' mode, where new files overwrite old ones.

We probably need a new module to enable 'full history clone' mode, that would replace `raf` in the case where the user wants to keep past versions.

**Comment by juliangruber** [comment]
we can actually modify a file's mtime using [fs#utimes](https://nodejs.org/docs/latest/api/fs.html#fs_fs_utimes_path_atime_mtime_callback), so the file can match. i'll give it a go adding it to raf and hyperdrive.

**Comment by juliangruber** [comment]
disadvantage: it's not an atomic operation since we need to first write to the file, then change its mtime

**Comment by juliangruber** [comment]
it's actually possible to do so in an atomic step if we first clone the file, then write, touch and replace.

@mafintosh what do you think?
